server:
  port: 8080

mybatis:
  type-aliases-package: com.gxwz.syschronicdisease.entity

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/medicalsystemdb?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456

  security:
    filter:
      order: -100

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      field-strategy: NOT_EMPTY
      db-type: MYSQL

configuration:
  map-underscore-to-camel-case: true
  call-setters-on-nulls: true
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


