CREATE TABLE IF NOT EXISTS chronic_policy (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    year INT NOT NULL COMMENT '年度',
    cap_amount DECIMAL(10,2) NOT NULL COMMENT '封顶线（元）',
    reimbursement_rate DECIMAL(5,2) NOT NULL COMMENT '报销比例（%）',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_year (year) COMMENT '年度唯一索引'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='慢性病政策表'; 